apiVersion: apps/v1
kind: Deployment
metadata:
  name: monolith-api
  labels:
    app: monolith-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: monolith-api
  template:
    metadata:
      labels:
        app: monolith-api
    spec:
      containers:
        - name: monolith-api
          image: monolith-shop-api:1.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
          env:
            - name: DB_HOST
              value: postgres-service

            - name: DB_PORT
              value: "5432"

            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_USER

            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_PASSWORD

            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_DB
